### ISSUE TITLE
misunderstanding

### ISSUE THREAD

**Issue by Biggitybaked** [batuhanturker/Infoins#1]
It says:
Instagram information gathering tool for none private accounts and private accounts

I run script and I get this:
Gizli Hesap Olduğu için Postlara Ulaşılamıyor
Which means:
Can't Access Posts Because It's Private Account

Suprise surprise

**Comment by batuhanturker** [comment]
You can only see some points of private accounts I will combine with osintgram on second version of this tool please wait for second version and thanks for using my tool
